/**
 * Example script: Check token balance for an address.
 *
 * Usage:
 *   npx tsx check-balance.ts
 *
 * Requires .env with deployed contract details.
 */

import * as fs from "fs";
import * as path from "path";
import { config } from "dotenv";
import { hd, helpers, utils, config as lumosConfig } from "@ckb-lumos/lumos";

config({ path: path.resolve(__dirname, "../.env") });

import { CkbClient } from "../mcp-sdk/src/client";
import { getTokenBalance } from "../mcp-sdk/src/tools/balance";
import { computeScriptHash } from "../mcp-sdk/src/utils/hash";

const CKB_RPC_URL = process.env.CKB_RPC_URL || "http://127.0.0.1:8114";
const CKB_INDEXER_URL = process.env.CKB_INDEXER_URL || "http://127.0.0.1:8116";
const OWNER_PRIVATE_KEY = process.env.OWNER_PRIVATE_KEY!;
const XUDT_CODE_HASH = process.env.XUDT_CODE_HASH || "";
const XUDT_HASH_TYPE = (process.env.XUDT_HASH_TYPE || "data1") as "type" | "data" | "data1";
const OWNER_LOCK_HASH = process.env.OWNER_LOCK_HASH || "";

// Configuration — set the address to check, or leave empty to check owner's address
const CHECK_ADDRESS = "";

async function main() {
  // Use local devnet config generated by offckb
  const devnetConfig = JSON.parse(fs.readFileSync(path.resolve(__dirname, "../lumos_config.json"), "utf8"));
  lumosConfig.initializeConfig(devnetConfig);

  const client = new CkbClient({
    rpcUrl: CKB_RPC_URL,
    indexerUrl: CKB_INDEXER_URL,
  });

  // Account 0 lock script on devnet
  const lockScript = {
    codeHash: "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
    hashType: "type" as const,
    args: "0x4118c8c16749bf126b22468d030bf9de7da3717b",
  };

  const ownerLockHash = "0x7de82d61a7eb2ec82b0dc653e558ba120efcbfbb44dac87c12972d05bf250653";

  // xUDT type script for the tokens we minted
  const typeScript = {
    codeHash: XUDT_CODE_HASH,
    hashType: "data" as const, // Try data instead of data1
    args: ownerLockHash,
  };

  console.log("Using TypeScript:", JSON.stringify(typeScript, null, 2));

  try {
    console.log("Calling client.collectCells now...");
    const cells = await client.collectCells(lockScript, typeScript);
    console.log(`Found ${cells.length} cells.`);
    
    let totalBalance = 0n;
    for (const cell of cells) {
      if (cell.outputData && cell.outputData.length >= 34) {
        // Decode u128le from first 16 bytes of data
        const hex = cell.outputData.slice(2, 34);
        const buffer = Buffer.from(hex, 'hex');
        let amount = 0n;
        for (let i = 0; i < 16; i++) {
          amount += BigInt(buffer[i]) << BigInt(i * 8);
        }
        totalBalance += amount;
      }
    }

    console.log("\n=== Balance Result ===");
    console.log(`Balance: ${totalBalance.toString()}`);
    console.log(`UDT Cells: ${cells.length}`);
  } catch (error: any) {
    console.error("Balance check failed:");
    console.error(error);
    process.exit(1);
  }
}

main();
